//Gfx converted using Mollusk's PAGfx Converter

//This file contains all the .c, for easier inclusion in a project

#ifdef __cplusplus
extern "C" {
#endif


// Sprite files : 
#include "title2.c"
#include "scroll_position.c"
#include "flashing_eyes.c"
#include "flake.c"
#include "selected.c"
#include "selected_op.c"
#include "hide_box.c"
#include "build_menu.c"
#include "menu_continue.c"
#include "ingame_menu_arrow.c"
#include "ingame_menu_selected.c"
#include "stat_screen_selected.c"
#include "t_select24x24.c"
#include "selection.c"
#include "interface_selected.c"
#include "icons.c"
#include "icons_dark.c"
#include "s_arrow.c"
#include "s_cannon.c"
#include "s_firerock.c"
#include "s_icerock.c"
#include "s_mudrock.c"
#include "s_poisonrock.c"
#include "s_lightning.c"
#include "s_poison_lightning.c"
#include "s_fire_lightning.c"
#include "s_bullet.c"
#include "s_blaster_shot.c"
#include "s_blue_beam.c"
#include "s_blue_blast.c"
#include "s_blue_grenade.c"
#include "s_blue_psy.c"
#include "s_fire_blaster_shot.c"
#include "s_fire_breath.c"
#include "s_fire_spore.c"
#include "s_fire_virus.c"
#include "s_green_beam.c"
#include "s_green_blast.c"
#include "s_green_psy.c"
#include "s_greenflame_cannon.c"
#include "s_grenade.c"
#include "s_ice_blaster_shot.c"
#include "s_ice_breath.c"
#include "s_ice_spore.c"
#include "s_ice_virus.c"
#include "s_iceflame_cannon.c"
#include "s_magenta_blast.c"
#include "s_poison_blaster_shot.c"
#include "s_poison_breath.c"
#include "s_poison_spore.c"
#include "s_poison_virus.c"
#include "s_red_beam.c"
#include "s_red_blast.c"
#include "s_red_psy.c"
#include "s_redflame_cannon.c"
#include "s_rocket.c"
#include "s_static_blue.c"
#include "s_static_green.c"
#include "s_static_red.c"
#include "s_tornado.c"
#include "s_yellow_beam.c"
#include "s_yellow_grenade.c"
#include "s_yellow_psy.c"
#include "t_all_normal.c"
#include "m_peon.c"
#include "m_footman.c"
#include "m_peasant.c"
#include "m_dwarves.c"
#include "m_goblins.c"
#include "m_sheep.c"
#include "m_sheep_big.c"
#include "m_dragon.c"
#include "m_gryphon.c"
#include "m_daemon.c"
#include "m_helicopter.c"
#include "m_knight.c"
#include "m_mage.c"
#include "m_ogre.c"
#include "m_skeleton.c"
#include "m_archer.c"
#include "m_axethrower.c"
#include "m_death_knight.c"
#include "m_zeppelin.c"
#include "m_grunt.c"
#include "m_ballista.c"
#include "m_battleship.c"
#include "m_buffalo.c"
#include "m_catapult.c"
#include "m_cleric.c"
#include "m_elven_destroyer.c"
#include "m_elven_tanker.c"
#include "m_human_tanker.c"
#include "m_human_transport.c"
#include "m_juggernaut.c"
#include "m_necrolyte.c"
#include "m_orc_transport.c"
#include "m_seal.c"
#include "m_submarine.c"
#include "m_troll_destroyer.c"
#include "m_turtle.c"

// Background files : 
#include "title1.c"
#include "menu.c"
#include "credits.c"
#include "options.c"
#include "select_map.c"
#include "select_map_highscore.c"
#include "interface.c"
#include "ingame_full_menu.c"
#include "ingame_menu.c"
#include "stat_screen.c"
#include "map_presentation_simple.c"
#include "map_presentation.c"

// Palette files : 
#include "title2.pal.c"
#include "scroll_position.pal.c"
#include "flashing_eyes.pal.c"
#include "flake.pal.c"
#include "selected.pal.c"
#include "selected_op.pal.c"
#include "hide_box.pal.c"
#include "build_menu.pal.c"
#include "menu_continue.pal.c"
#include "ingame_menu_arrow.pal.c"
#include "ingame_menu_selected.pal.c"
#include "stat_screen_selected.pal.c"
#include "t_select24x24.pal.c"
#include "interface_selected.pal.c"
#include "icons.pal.c"
#include "icons_dark.pal.c"
#include "attacks.pal.c"
#include "t_all_normal.pal.c"
#include "t_all_frozen.pal.c"
#include "t_all_poison.pal.c"
#include "t_all_dark.pal.c"
#include "monsters.pal.c"
#include "monsters_froz.pal.c"
#include "monsters_green.pal.c"
#include "monsters_pois.pal.c"
#include "monsters_blue.pal.c"
#include "monsters_dark.pal.c"
#include "title1.pal.c"
#include "menu.pal.c"
#include "credits.pal.c"
#include "options.pal.c"
#include "select_map.pal.c"
#include "interface.pal.c"
#include "ingame_menu.pal.c"
#include "stat_screen.pal.c"
#include "map_presentation_simple.pal.c"
#include "map_presentation.pal.c"


#ifdef __cplusplus
}
#endif

